export const LOAD_DATA_INITIATION = 'LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
export const CLEAR_DATA_ERROR = 'CLEAR_DATA_ERROR';
export const RECEIVE_GET = 'RECEIVE_GET';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const RECEIVE_DISPATCH_PRIMARY = 'RECEIVE_DISPATCH_PRIMARY'; // 一次发运
export const RECEIVE_DISPATCH_SECONDARY = 'RECEIVE_DISPATCH_SECONDARY'; // 二次发运

export const RECEIVE_DISPATCH_FACTORY = 'RECEIVE_DISPATCH_FACTORY'; // 旧件返工厂
export const RECEIVE_DISPATCH_INDUSTRY = 'RECEIVE_DISPATCH_INDUSTRY'; // 旧件返工贸

export const RECEIVE_DISPATCH_CROSSING = 'RECEIVE_DISPATCH_CROSSING'; // 过站发运

export const RECEIVE_DISPATCH = 'RECEIVE_DISPATCH'; // 发运操作费
export const RECEIVE_STORAGE = 'RECEIVE_STORAGE'; // 过站操作费

export const RECEIVE_REPORT_PRIMARY = 'RECEIVE_REPORT_PRIMARY'; // 一级报表
export const RECEIVE_REPORT_SECONDARY = 'RECEIVE_REPORT_SECONDARY'; // 二级级报表
export const RECEIVE_REPORT_TERTIARY = 'RECEIVE_REPORT_TERTIARY'; // 三级级报表
