export default [
  { key: 'text', title: '文字' },
  { key: 'title', title: '标题' },
  { key: 'image', title: '单张图片' },
  { key: 'multipleImage', title: '多张图片' },
  { key: 'thermalZone', title: '图片热区' },
  { key: 'swiper', title: '轮播' },
  { key: 'tabs', title: '标签页' },
  { key: 'navigationBar', title: '导航栏' },
  { key: 'noticeCard', title: '消息卡片' },
  { key: 'articleCard', title: '文章卡片' },
  { key: 'messageList', title: '资讯列表' },
  { key: 'photoArticleLinkage', title: '图片联动' },
  { key: 'coupon', title: '领劵' },
  { key: 'gift', title: '新人礼包' },
  { key: 'seckill', title: '整点秒杀' },
  { key: 'goodsCard', title: '商品卡片' },
  { key: 'goodsSlider', title: '侧滑商品' },
]
