export default {
  textDesign: import('./text'),
  imageDesign: import('./image'),
  thermalZoneDesign: import('./thermalZone'),
  swiperDesign: import('./swiper'),
  tabsDesign: import('./tabsDesign'),
  noticeCardDesign: import('./notice'),
  messageListDesign: import('./messageListDesign'),
  articleCardDesign: import('./articleCard'),
  couponDesign: import('./couponDesign'),
  titleDesign: import('./title'),
  goodsCardDesign: import('./goodsCardDesign'),
  goodsSliderDesign: import('./goodsSliderDesign'),
  multImageDesign: import('./multImageDesign'),
  photoArticleLinkageDesign:import('./photoArticleLinkage'),
  navigationBarDesign:import('./navigationBar'),
  giftDesign: import('./gift'),
  seckillDesign: import('./seckill'),
  error: import('./error')
}
